variables:
  ARGOPKGS : "https://xgitlab.cels.anl.gov/argo/argopkgs/-/archive/master/argopkgs-master.tar.gz"
  EXTRA: "--excit ./."

stages:
  - quality
  - build

include:
  - https://xgitlab.cels.anl.gov/argo/argopkgs/raw/master/gitlab-ci/repoquality.yml
  - https://xgitlab.cels.anl.gov/argo/argopkgs/raw/master/gitlab-ci/excit.yml
