name: builds
on:
  push:
    branches:
      - master
  pull_request:

env:
  CFLAGS: "-std=c99 -pedantic -Wall -Wextra -Werror -Wno-unused-but-set-parameter -Wno-builtin-declaration-mismatch"
  VERBOSE: 1
jobs:
  generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc make autoconf automake libtool pkgconf
      - name: configure
        run: |
          ./autogen.sh
          mkdir build
          ./configure --prefix=`pwd`/build
      - run: make
      - run: make check
      - run: make install
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: generic
          path: |
            config.log
            tests/*.log
  out-of-tree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc make autoconf automake libtool pkgconf libhwloc-dev
      - name: configure
        run: |
          ./autogen.sh
          mkdir out
          cd out
          mkdir build
          ../configure --prefix=`pwd`/build --without-rocm
      - run: make
        working-directory: out
      - run: make check
        working-directory: out
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: out-of-tree
          path: |
            out/config.log
            out/tests/*.log
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc make autoconf automake libtool pkgconf valgrind
      - name: configure
        run: |
          ./autogen.sh
          mkdir build
          ./configure --prefix=`pwd`/build --enable-valgrind
      - run: make
      - run: make check-valgrind
        env:
          VALGRIND_SUPPRESSIONS_FILES: ${{ github.workspace }}/.valgrind.supp
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: valgrind
          path: |
            config.log
            tests/*.log
  distcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - run: sudo apt-get update
      - run: sudo apt-get install -y gcc make autoconf automake libtool pkgconf
      - name: configure
        run: |
          ./autogen.sh
          mkdir build
          ./configure --prefix=`pwd`/build
      - run: make distcheck
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: distcheck
          path: |
            config.log
            tests/*.log
